# Generated by Django 6.0.4 on 2026-04-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Reception', 'Reception'), ('Pharmacy', 'Pharmacy'), ('Laboratory', 'Laboratory'), ('HR', 'HR'), ('Other', 'Other')], default='Reception', max_length=50)),
                ('shift_timing', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Night', 'Night')], default='Morning', max_length=20)),
            ],
        ),
    ]
